version: '1'
services:
  redis:
    image: 'redis/redis-stack:latest'
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redisData:/app/local_folder
    environment:
      - REDIS_ARGS= --save 20 1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  data_injestion:
    container_name: data_injestion
    build:
      context: ./DataInjestion
      dockerfile: Dockerfile
    depends_on:
      - redis
    network_mode: service:redis

  analytics:
    container_name: analytics
    build:
      context: ./Analytics
      dockerfile: Dockerfile
    depends_on:
      - redis
      - data_injestion
    network_mode: service:redis

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    
  spark_ml:
    image: bde2020/spark-base:3.3.0-hadoop3.3
    container_name: spark_ml
    build:
      context: ./SparkML
      dockerfile: Dockerfile
    depends_on:
      - spark-master
      - data_injestion
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./SparkML:/app/sparkml
    network_mode: service:redis
