version: '1'
services:
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./redisData:/redisData
    environment:
      - REDIS_ARGS= --save 20 1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  datainjestion:
    build:
      context: ./DataInjestion
      dockerfile: Dockerfile
    depends_on:
      - redis