version: '1'
services:
  redis:
    image: 'redis/redis-stack:latest'
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redisData:/volumes/redisVol
    environment:
      - REDIS_ARGS= --save 20 1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  data_injestion:
    container_name: data_injestion
    build:
      context: ./DataInjestion
      dockerfile: Dockerfile
    depends_on:
      - redis
    network_mode: service:redis

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  analytics:
    container_name: analytics
    build:
      context: ./Analytics
      dockerfile: Dockerfile
    depends_on:
      - redis
      - spark-master
      - spark-worker
    network_mode: service:redis